---
name: Code Review - Linting & Link Checks

on:
  pull_request:
    branches:
      - main
      - dev-tools
  workflow_dispatch: {}

permissions:
  contents: read
  packages: read

jobs:
  lint:
    permissions:
      statuses: write
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run github/super-linter
        uses: github/super-linter@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          VALIDATE_ALL_CODEBASE: false
          # Need to define main branch as default is set to master in super-linter
          DEFAULT_BRANCH: main
          # Enable setting the status of each individual linter run in the Checks section of a pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The following linter types will be enabled:
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_EDITORCONFIG: true
          FILTER_REGEX_EXCLUDE: ".*docs/themes/hugo-geekdoc/.*"

  markdown_link_check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # main
        with:
          fetch-depth: 0

      - name: Check links in markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.15
        with:
          config-file: ".github/linters/mlc_config.json"
          use-verbose-mode: "yes"
          use-quiet-mode: "yes"
          check-modified-files-only: "yes"
          base-branch: "main"

